/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoproyecto;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import source.ListaEquipos;

/**
 *
 * @author E2
 */
public class VentanaManual extends javax.swing.JFrame {

    /**
     * Creates new form VentanaManual
     */
    String[] paises = new String[32];
    String paisesA[] = new String[4];
    String paisesB[] = new String[4];
    String paisesC[] = new String[4];
    String paisesD[] = new String[4];
    String paisesE[] = new String[4];
    String paisesF[] = new String[4];
    String paisesG[] = new String[4];
    String paisesH[] = new String[4];
    
    
    int ca = 0;
    int cb = 0;
    int cc = 0;
    int cd = 0;
    int ce = 0;
    int cf = 0;
    int cg = 0;
    int ch = 0;

    public VentanaManual() {
        initComponents();
        cargarEquipos();

    }

    public void cargarEquipos() {

        for (int i = 0; i < 32; i++) {
            paises[i] = ListaEquipos.listaEquipos[i].getNombre();
        }
        jlPaises.setListData(paises);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlPaises = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlGrupo1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlGrupo2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlGrupo3 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlGrupo4 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlGrupo5 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlGrupo6 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlGrupo7 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jlGrupo8 = new javax.swing.JList<>();
        btnRegresar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnGrC = new javax.swing.JButton();
        btnGrG = new javax.swing.JButton();
        btnGrD = new javax.swing.JButton();
        btngrH = new javax.swing.JButton();
        btnGrB = new javax.swing.JButton();
        btnGrF = new javax.swing.JButton();
        btnGrA = new javax.swing.JButton();
        btnGrE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jlPaises.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlPaises.setOpaque(false);
        jScrollPane1.setViewportView(jlPaises);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 200, 510);

        jScrollPane2.setOpaque(false);

        jlGrupo1.setOpaque(false);
        jScrollPane2.setViewportView(jlGrupo1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(280, 20, 140, 90);

        jlGrupo2.setOpaque(false);
        jScrollPane3.setViewportView(jlGrupo2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(440, 20, 150, 90);

        jlGrupo3.setOpaque(false);
        jScrollPane4.setViewportView(jlGrupo3);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(610, 20, 150, 90);

        jlGrupo4.setOpaque(false);
        jScrollPane5.setViewportView(jlGrupo4);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(280, 150, 140, 90);

        jlGrupo5.setOpaque(false);
        jScrollPane6.setViewportView(jlGrupo5);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(440, 150, 150, 90);

        jlGrupo6.setOpaque(false);
        jScrollPane7.setViewportView(jlGrupo6);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(610, 150, 150, 90);

        jlGrupo7.setOpaque(false);
        jScrollPane8.setViewportView(jlGrupo7);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(280, 280, 140, 90);

        jlGrupo8.setOpaque(false);
        jScrollPane9.setViewportView(jlGrupo8);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(440, 280, 150, 90);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(280, 430, 160, 30);

        btnIniciar.setText("INICIAR CAMPEONATO");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(560, 430, 160, 30);

        btnGrC.setText("Group C");
        btnGrC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrCActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrC);
        btnGrC.setBounds(611, 320, 90, 30);

        btnGrG.setText("Group G");
        btnGrG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrGActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrG);
        btnGrG.setBounds(701, 320, 80, 30);

        btnGrD.setText("Group D");
        btnGrD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrDActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrD);
        btnGrD.setBounds(611, 350, 90, 40);

        btngrH.setText("Group H");
        btngrH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrHActionPerformed(evt);
            }
        });
        getContentPane().add(btngrH);
        btngrH.setBounds(701, 350, 80, 40);

        btnGrB.setText("Group B");
        btnGrB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrBActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrB);
        btnGrB.setBounds(611, 290, 90, 30);

        btnGrF.setText("Group F");
        btnGrF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrFActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrF);
        btnGrF.setBounds(701, 290, 80, 30);

        btnGrA.setText("Group A");
        btnGrA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrAActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrA);
        btnGrA.setBounds(611, 260, 90, 30);

        btnGrE.setText("Group E");
        btnGrE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrEActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrE);
        btnGrE.setBounds(701, 260, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMundial4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 550);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 410, 34, 14);

        setSize(new java.awt.Dimension(800, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaSeleccionarModo regresar = new VentanaSeleccionarModo();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        VentanaFecha1Manual fase = new VentanaFecha1Manual();
        fase.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnGrAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrAActionPerformed
        
        if (ca < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesA[ca] = jlPaises.getSelectedValue();
            jlGrupo1.setListData(paisesA);
            paises[i] = "";
            jlPaises.setListData(paises);
            ca++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }


    }//GEN-LAST:event_btnGrAActionPerformed

    private void btnGrEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrEActionPerformed
        if (ce < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesE[ce] = jlPaises.getSelectedValue();
            jlGrupo5.setListData(paisesE);
            paises[i] = "";
            jlPaises.setListData(paises);
            ce++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrEActionPerformed

    private void btnGrBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrBActionPerformed
       if (cb < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesB[cb] = jlPaises.getSelectedValue();
            jlGrupo2.setListData(paisesB);
            paises[i] = "";
            jlPaises.setListData(paises);
            cb++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrBActionPerformed

    private void btnGrCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrCActionPerformed
        if (cc < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesC[cc] = jlPaises.getSelectedValue();
            jlGrupo3.setListData(paisesC);
            paises[i] = "";
            jlPaises.setListData(paises);
            cc++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrCActionPerformed

    private void btnGrDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrDActionPerformed
        if (cd < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesD[cd] = jlPaises.getSelectedValue();
            jlGrupo4.setListData(paisesD);
            paises[i] = "";
            jlPaises.setListData(paises);
            cd++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrDActionPerformed

    private void btnGrFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrFActionPerformed
        if (cf< 4) {
            int i = jlPaises.getSelectedIndex();

            paisesF[cf] = jlPaises.getSelectedValue();
            jlGrupo6.setListData(paisesF);
            paises[i] = "";
            jlPaises.setListData(paises);
            cf++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrFActionPerformed

    private void btnGrGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrGActionPerformed
       if (cg < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesG[cg] = jlPaises.getSelectedValue();
            jlGrupo7.setListData(paisesG);
            paises[i] = "";
            jlPaises.setListData(paises);
            cg++;
        }else {
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrGActionPerformed

    private void btngrHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrHActionPerformed
        if (ch < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesH[ch] = jlPaises.getSelectedValue();
            jlGrupo8.setListData(paisesH);
            paises[i] = "";
            jlPaises.setListData(paises);
            ch++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btngrHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaManual().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrA;
    private javax.swing.JButton btnGrB;
    private javax.swing.JButton btnGrC;
    private javax.swing.JButton btnGrD;
    private javax.swing.JButton btnGrE;
    private javax.swing.JButton btnGrF;
    private javax.swing.JButton btnGrG;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btngrH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> jlGrupo1;
    private javax.swing.JList<String> jlGrupo2;
    private javax.swing.JList<String> jlGrupo3;
    private javax.swing.JList<String> jlGrupo4;
    private javax.swing.JList<String> jlGrupo5;
    private javax.swing.JList<String> jlGrupo6;
    private javax.swing.JList<String> jlGrupo7;
    private javax.swing.JList<String> jlGrupo8;
    private javax.swing.JList<String> jlPaises;
    // End of variables declaration//GEN-END:variables
}
