/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoproyecto;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ferna
 */
public class VentanaAzarOctavos extends javax.swing.JFrame {
    Fondo fondo;
    
    public VentanaAzarOctavos() {
        fondo =new Fondo();
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jTextField10 = new javax.swing.JTextField();
        scrollPane2 = new java.awt.ScrollPane();
        jTextField4 = new javax.swing.JTextField();
        scrollPane3 = new java.awt.ScrollPane();
        jTextField3 = new javax.swing.JTextField();
        scrollPane4 = new java.awt.ScrollPane();
        jTextField5 = new javax.swing.JTextField();
        scrollPane5 = new java.awt.ScrollPane();
        jTextField2 = new javax.swing.JTextField();
        scrollPane6 = new java.awt.ScrollPane();
        jTextField30 = new javax.swing.JTextField();
        scrollPane7 = new java.awt.ScrollPane();
        jTextField14 = new javax.swing.JTextField();
        scrollPane8 = new java.awt.ScrollPane();
        jTextField8 = new javax.swing.JTextField();
        scrollPane9 = new java.awt.ScrollPane();
        jTextField6 = new javax.swing.JTextField();
        scrollPane10 = new java.awt.ScrollPane();
        jTextField27 = new javax.swing.JTextField();
        scrollPane11 = new java.awt.ScrollPane();
        jTextField7 = new javax.swing.JTextField();
        scrollPane13 = new java.awt.ScrollPane();
        jTextField9 = new javax.swing.JTextField();
        scrollPane14 = new java.awt.ScrollPane();
        jTextField12 = new javax.swing.JTextField();
        scrollPane16 = new java.awt.ScrollPane();
        jTextField18 = new javax.swing.JTextField();
        scrollPane17 = new java.awt.ScrollPane();
        jTextField13 = new javax.swing.JTextField();
        scrollPane15 = new java.awt.ScrollPane();
        jTextField25 = new javax.swing.JTextField();
        scrollPane19 = new java.awt.ScrollPane();
        jTextField21 = new javax.swing.JTextField();
        scrollPane22 = new java.awt.ScrollPane();
        jTextField29 = new javax.swing.JTextField();
        scrollPane23 = new java.awt.ScrollPane();
        jTextField23 = new javax.swing.JTextField();
        scrollPane24 = new java.awt.ScrollPane();
        jTextField11 = new javax.swing.JTextField();
        scrollPane25 = new java.awt.ScrollPane();
        jTextField24 = new javax.swing.JTextField();
        scrollPane26 = new java.awt.ScrollPane();
        jTextField17 = new javax.swing.JTextField();
        scrollPane27 = new java.awt.ScrollPane();
        jTextField22 = new javax.swing.JTextField();
        scrollPane28 = new java.awt.ScrollPane();
        jTextField31 = new javax.swing.JTextField();
        scrollPane21 = new java.awt.ScrollPane();
        jTextField28 = new javax.swing.JTextField();
        scrollPane29 = new java.awt.ScrollPane();
        jTextField26 = new javax.swing.JTextField();
        scrollPane12 = new java.awt.ScrollPane();
        jTextField15 = new javax.swing.JTextField();
        scrollPane30 = new java.awt.ScrollPane();
        jTextField19 = new javax.swing.JTextField();
        btnOctavos = new javax.swing.JButton();
        btnCuartos = new javax.swing.JButton();
        btnSemifinal = new javax.swing.JButton();
        btnRegresar3 = new javax.swing.JButton();
        btnFinal = new javax.swing.JButton();
        txtCampeon = new javax.swing.JTextField();
        semi2 = new javax.swing.JTextField();
        Semi1 = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jTextField10.setEditable(false);
        scrollPane1.add(jTextField10);

        jTextField4.setEditable(false);
        scrollPane2.add(jTextField4);

        jTextField3.setEditable(false);
        scrollPane3.add(jTextField3);

        jTextField5.setEditable(false);
        scrollPane4.add(jTextField5);

        jTextField2.setEditable(false);
        scrollPane5.add(jTextField2);

        jTextField30.setEditable(false);
        scrollPane6.add(jTextField30);

        jTextField14.setEditable(false);
        scrollPane7.add(jTextField14);

        jTextField8.setEditable(false);
        scrollPane8.add(jTextField8);

        jTextField6.setEditable(false);
        scrollPane9.add(jTextField6);

        jTextField27.setEditable(false);
        scrollPane10.add(jTextField27);

        jTextField7.setEditable(false);
        scrollPane11.add(jTextField7);

        jTextField9.setEditable(false);
        scrollPane13.add(jTextField9);

        jTextField12.setEditable(false);
        scrollPane14.add(jTextField12);

        jTextField18.setEditable(false);
        scrollPane16.add(jTextField18);

        jTextField13.setEditable(false);
        scrollPane17.add(jTextField13);

        jTextField25.setEditable(false);
        scrollPane15.add(jTextField25);

        jTextField21.setEditable(false);
        scrollPane19.add(jTextField21);

        jTextField29.setEditable(false);
        scrollPane22.add(jTextField29);

        jTextField23.setEditable(false);
        scrollPane23.add(jTextField23);

        jTextField11.setEditable(false);
        scrollPane24.add(jTextField11);

        jTextField24.setEditable(false);
        scrollPane25.add(jTextField24);

        jTextField17.setEditable(false);
        scrollPane26.add(jTextField17);

        jTextField22.setEditable(false);
        scrollPane27.add(jTextField22);

        jTextField31.setEditable(false);
        scrollPane28.add(jTextField31);

        jTextField28.setEditable(false);
        scrollPane21.add(jTextField28);

        jTextField26.setEditable(false);
        scrollPane29.add(jTextField26);

        jTextField15.setEditable(false);
        scrollPane12.add(jTextField15);

        jTextField19.setEditable(false);
        scrollPane30.add(jTextField19);

        btnOctavos.setText("SIMULAR OCTAVOS");
        btnOctavos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOctavosMouseClicked(evt);
            }
        });
        btnOctavos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOctavosActionPerformed(evt);
            }
        });

        btnCuartos.setText("SIMULAR CUARTOS");
        btnCuartos.setEnabled(false);
        btnCuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuartosMouseClicked(evt);
            }
        });
        btnCuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuartosActionPerformed(evt);
            }
        });

        btnSemifinal.setText("SIMULAR SEMIFINALES");
        btnSemifinal.setEnabled(false);
        btnSemifinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSemifinalMouseClicked(evt);
            }
        });
        btnSemifinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemifinalActionPerformed(evt);
            }
        });

        btnRegresar3.setText("REGRESAR");
        btnRegresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar3ActionPerformed(evt);
            }
        });

        btnFinal.setText("SIMULAR LA FINAL");
        btnFinal.setEnabled(false);
        btnFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalMouseClicked(evt);
            }
        });
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        txtCampeon.setEditable(false);

        semi2.setEditable(false);

        Semi1.setEditable(false);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(scrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(scrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Semi1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 92, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(416, 416, 416)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(scrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(66, 66, 66))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCampeon, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(semi2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(237, 237, 237))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(323, 323, 323)
                                        .addComponent(scrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)
                                        .addComponent(scrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(244, 244, 244)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnOctavos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(btnCuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSemifinal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(scrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(scrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(scrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(scrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(scrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(scrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtCampeon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(8, 8, 8)
                                        .addComponent(scrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(scrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(81, 81, 81))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(semi2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Semi1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(scrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnOctavos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSemifinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void btnOctavosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOctavosActionPerformed
         FaseFinal.verClasificados();
        jTextField2.setText(FaseFinal.octavos[0]);
        jTextField3.setText(FaseFinal.octavos[1]);
        jTextField4.setText(FaseFinal.octavos[2]);
        jTextField5.setText(FaseFinal.octavos[3]);
        jTextField6.setText(FaseFinal.octavos[4]);
        jTextField7.setText(FaseFinal.octavos[5]);
        jTextField8.setText(FaseFinal.octavos[6]);
        jTextField9.setText(FaseFinal.octavos[7]);
        jTextField11.setText(FaseFinal.octavos[8]);
        jTextField17.setText(FaseFinal.octavos[9]);
        jTextField23.setText(FaseFinal.octavos[10]);
        jTextField24.setText(FaseFinal.octavos[11]);
        jTextField31.setText(FaseFinal.octavos[12]);
        jTextField26.setText(FaseFinal.octavos[13]);
        jTextField27.setText(FaseFinal.octavos[14]);
        jTextField28.setText(FaseFinal.octavos[15]);
    }//GEN-LAST:event_btnOctavosActionPerformed

    
    private void btnCuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuartosActionPerformed
        FaseFinal.generarResultadosOctavosAleatoriamente100realNoFakeUnLink();
          jTextField10.setText(FaseFinal.cuartos[0]);
        jTextField12.setText(FaseFinal.cuartos[1]);
        jTextField14.setText(FaseFinal.cuartos[2]);
        jTextField15.setText(FaseFinal.cuartos[3]);
        jTextField30.setText(FaseFinal.cuartos[4]);
        jTextField29.setText(FaseFinal.cuartos[5]);
        jTextField25.setText(FaseFinal.cuartos[6]);
        jTextField22.setText(FaseFinal.cuartos[7]);
    }//GEN-LAST:event_btnCuartosActionPerformed

    private void btnSemifinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemifinalActionPerformed
         FaseFinal.generarResultadosCuartosFinal();
        jTextField13.setText(FaseFinal.semifinal[0]);
        Semi1.setText(FaseFinal.semifinal[1]);
        jTextField21.setText(FaseFinal.semifinal[2]);
        semi2.setText(FaseFinal.semifinal[3]);
        String salida="";
        for (int i = 0; i < 4; i++) {
            salida+=FaseFinal.semifinal[i];
        }
    }//GEN-LAST:event_btnSemifinalActionPerformed

    private void btnRegresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar3ActionPerformed
    VentanaAzarFecha1 regresar = new VentanaAzarFecha1();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresar3ActionPerformed

    private void btnOctavosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOctavosMouseClicked
        // TODO add your handling code here:
        btnOctavos.setEnabled(false);
        btnCuartos.setEnabled(true);
    }//GEN-LAST:event_btnOctavosMouseClicked

    private void btnCuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuartosMouseClicked
        // TODO add your handling code here:
        btnCuartos.setEnabled(false);
        btnSemifinal.setEnabled(true);
    }//GEN-LAST:event_btnCuartosMouseClicked

    private void btnSemifinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSemifinalMouseClicked
        // TODO add your handling code here:
        btnSemifinal.setEnabled(false);
        btnFinal.setEnabled(true);
        
    }//GEN-LAST:event_btnSemifinalMouseClicked

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        // TODO add your handling code here:
        FaseFinal.generarResultadosSeminifal();
        FaseFinal.generarResultadosGranFinal();
        jTextField18.setText(FaseFinal.Granfinal[0]);
        jTextField19.setText(FaseFinal.Granfinal[1]);
        txtCampeon.setText(FaseFinal.campeon[0]);
        JOptionPane.showMessageDialog(null, "!CAMPEÓN¡\n"+FaseFinal.campeon[0]);
    }//GEN-LAST:event_btnFinalActionPerformed

    private void btnFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalMouseClicked
        // TODO add your handling code here:
        btnFinal.setEnabled(false);
    }//GEN-LAST:event_btnFinalMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarOctavos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarOctavos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarOctavos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarOctavos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAzarOctavos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Semi1;
    private javax.swing.JButton btnCuartos;
    public javax.swing.JButton btnFinal;
    private javax.swing.JButton btnOctavos;
    private javax.swing.JButton btnRegresar3;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSemifinal;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane10;
    private java.awt.ScrollPane scrollPane11;
    private java.awt.ScrollPane scrollPane12;
    private java.awt.ScrollPane scrollPane13;
    private java.awt.ScrollPane scrollPane14;
    private java.awt.ScrollPane scrollPane15;
    private java.awt.ScrollPane scrollPane16;
    private java.awt.ScrollPane scrollPane17;
    private java.awt.ScrollPane scrollPane19;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane21;
    private java.awt.ScrollPane scrollPane22;
    private java.awt.ScrollPane scrollPane23;
    private java.awt.ScrollPane scrollPane24;
    private java.awt.ScrollPane scrollPane25;
    private java.awt.ScrollPane scrollPane26;
    private java.awt.ScrollPane scrollPane27;
    private java.awt.ScrollPane scrollPane28;
    private java.awt.ScrollPane scrollPane29;
    private java.awt.ScrollPane scrollPane3;
    private java.awt.ScrollPane scrollPane30;
    private java.awt.ScrollPane scrollPane4;
    private java.awt.ScrollPane scrollPane5;
    private java.awt.ScrollPane scrollPane6;
    private java.awt.ScrollPane scrollPane7;
    private java.awt.ScrollPane scrollPane8;
    private java.awt.ScrollPane scrollPane9;
    private javax.swing.JTextField semi2;
    private javax.swing.JTextField txtCampeon;
    // End of variables declaration//GEN-END:variables
public class Fondo extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen = new ImageIcon(getClass().getResource("/imagenes/FondoOctavos.jpg")).getImage();
        g.drawImage(imagen, 0, 0,getWidth(),getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
    
}

}
