/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoproyecto;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import source.*;


/**
 *
 * @author E2
 */
public class VentanaManual extends javax.swing.JFrame {

    /**
     * Creates new form VentanaManual
     */
    String[] paises = new String[32];
    String paisesA[] = new String[4];
    String paisesB[] = new String[4];
    String paisesC[] = new String[4];
    String paisesD[] = new String[4];
    String paisesE[] = new String[4];
    String paisesF[] = new String[4];
    String paisesG[] = new String[4];
    String paisesH[] = new String[4];
    
    
    int ca = 0;
    int cb = 0;
    int cc = 0;
    int cd = 0;
    int ce = 0;
    int cf = 0;
    int cg = 0;
    int ch = 0;

    public VentanaManual() {
        EquiposFaseGrupos.iniciarCrearGrupos();
        initComponents();
        cargarEquipos();

    }

    public void cargarEquipos() {

        for (int i = 0; i < 32; i++) {
            paises[i] = ListaEquipos.listaEquipos[i].getNombre();
        }
        jlPaises.setListData(paises);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlPaises = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlGrupo1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlGrupo2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlGrupo3 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlGrupo4 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlGrupo5 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlGrupo6 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlGrupo7 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jlGrupo8 = new javax.swing.JList<>();
        btnRegresar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnGrC = new javax.swing.JButton();
        btnGrG = new javax.swing.JButton();
        btnGrD = new javax.swing.JButton();
        btngrH = new javax.swing.JButton();
        btnGrB = new javax.swing.JButton();
        btnGrF = new javax.swing.JButton();
        btnGrA = new javax.swing.JButton();
        btnGrE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jlPaises.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlPaises.setOpaque(false);
        jScrollPane1.setViewportView(jlPaises);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 200, 490);

        jScrollPane2.setOpaque(false);

        jlGrupo1.setOpaque(false);
        jScrollPane2.setViewportView(jlGrupo1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(270, 40, 150, 90);

        jlGrupo2.setOpaque(false);
        jScrollPane3.setViewportView(jlGrupo2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(270, 170, 150, 90);

        jlGrupo3.setOpaque(false);
        jScrollPane4.setViewportView(jlGrupo3);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(270, 300, 150, 90);

        jlGrupo4.setOpaque(false);
        jScrollPane5.setViewportView(jlGrupo4);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(270, 420, 150, 90);

        jlGrupo5.setOpaque(false);
        jScrollPane6.setViewportView(jlGrupo5);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(440, 40, 150, 90);

        jlGrupo6.setOpaque(false);
        jScrollPane7.setViewportView(jlGrupo6);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(440, 420, 150, 90);

        jlGrupo7.setOpaque(false);
        jScrollPane8.setViewportView(jlGrupo7);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(440, 300, 150, 90);

        jlGrupo8.setOpaque(false);
        jScrollPane9.setViewportView(jlGrupo8);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(440, 170, 150, 90);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(620, 480, 160, 30);

        btnIniciar.setText("INICIAR CAMPEONATO");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(620, 430, 160, 40);

        btnGrC.setText("Grupo C");
        btnGrC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrCActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrC);
        btnGrC.setBounds(650, 140, 90, 30);

        btnGrG.setText("Grupo G");
        btnGrG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrGActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrG);
        btnGrG.setBounds(650, 300, 90, 30);

        btnGrD.setText("Grupo D");
        btnGrD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrDActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrD);
        btnGrD.setBounds(650, 180, 90, 30);

        btngrH.setText("Grupo H");
        btngrH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrHActionPerformed(evt);
            }
        });
        getContentPane().add(btngrH);
        btngrH.setBounds(650, 340, 90, 30);

        btnGrB.setText("Grupo B");
        btnGrB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrBActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrB);
        btnGrB.setBounds(650, 100, 90, 30);

        btnGrF.setText("Grupo F");
        btnGrF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrFActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrF);
        btnGrF.setBounds(650, 260, 90, 30);

        btnGrA.setText("Grupo  A");
        btnGrA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrAActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrA);
        btnGrA.setBounds(650, 60, 90, 30);

        btnGrE.setText("Grupo E");
        btnGrE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrEActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrE);
        btnGrE.setBounds(650, 220, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GRUPO A");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 20, 70, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GRUPO E");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 20, 70, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GRUPO B");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 150, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GRUPO F");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 150, 70, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GRUPO C");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 280, 70, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GRUPO G");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 280, 70, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GRUPO D");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 400, 70, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GRUPO H");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 400, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMundial4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 550);

        setSize(new java.awt.Dimension(812, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaSeleccionarModo regresar = new VentanaSeleccionarModo();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        VentanaFecha1Manual fase = new VentanaFecha1Manual();
        fase.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnGrAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrAActionPerformed
        
        if (ca < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesA[ca] = jlPaises.getSelectedValue();
            jlGrupo1.setListData(paisesA);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoA.addEquipo(new Nodo(new Equipo(paisesA[ca])));
            ca++;
            
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }


    }//GEN-LAST:event_btnGrAActionPerformed

    private void btnGrEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrEActionPerformed
        if (ce < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesE[ce] = jlPaises.getSelectedValue();
            jlGrupo5.setListData(paisesE);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoE.addEquipo(new Nodo(new Equipo(paisesE[ce])));
            ce++;
            
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrEActionPerformed

    private void btnGrBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrBActionPerformed
       if (cb < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesB[cb] = jlPaises.getSelectedValue();
            jlGrupo2.setListData(paisesB);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoB.addEquipo(new Nodo(new Equipo(paisesB[cb])));
            cb++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrBActionPerformed

    private void btnGrCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrCActionPerformed
        if (cc < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesC[cc] = jlPaises.getSelectedValue();
            jlGrupo3.setListData(paisesC);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoC.addEquipo(new Nodo(new Equipo(paisesC[cc])));
            cc++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrCActionPerformed

    private void btnGrDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrDActionPerformed
        if (cd < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesD[cd] = jlPaises.getSelectedValue();
            jlGrupo4.setListData(paisesD);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoD.addEquipo(new Nodo(new Equipo(paisesD[cd])));
            cd++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrDActionPerformed

    private void btnGrFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrFActionPerformed
        if (cf< 4) {
            int i = jlPaises.getSelectedIndex();

            paisesF[cf] = jlPaises.getSelectedValue();
            jlGrupo6.setListData(paisesF);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoF.addEquipo(new Nodo(new Equipo(paisesF[cf])));
            cf++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrFActionPerformed

    private void btnGrGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrGActionPerformed
       if (cg < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesG[cg] = jlPaises.getSelectedValue();
            jlGrupo7.setListData(paisesG);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoG.addEquipo(new Nodo(new Equipo(paisesG[cg])));
            cg++;
        }else {
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btnGrGActionPerformed

    private void btngrHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrHActionPerformed
        if (ch < 4) {
            int i = jlPaises.getSelectedIndex();

            paisesH[ch] = jlPaises.getSelectedValue();
            jlGrupo8.setListData(paisesH);
            paises[i] = "";
            jlPaises.setListData(paises);
            EquiposFaseGrupos.grupoH.addEquipo(new Nodo(new Equipo(paisesH[ch])));
            ch++;
        }else{
            JOptionPane.showMessageDialog(null,"No se puede agregar mas equipos");
        }
    }//GEN-LAST:event_btngrHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaManual().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrA;
    private javax.swing.JButton btnGrB;
    private javax.swing.JButton btnGrC;
    private javax.swing.JButton btnGrD;
    private javax.swing.JButton btnGrE;
    private javax.swing.JButton btnGrF;
    private javax.swing.JButton btnGrG;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btngrH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> jlGrupo1;
    private javax.swing.JList<String> jlGrupo2;
    private javax.swing.JList<String> jlGrupo3;
    private javax.swing.JList<String> jlGrupo4;
    private javax.swing.JList<String> jlGrupo5;
    private javax.swing.JList<String> jlGrupo6;
    private javax.swing.JList<String> jlGrupo7;
    private javax.swing.JList<String> jlGrupo8;
    private javax.swing.JList<String> jlPaises;
    // End of variables declaration//GEN-END:variables
}
