
package demoproyecto;


import source.*;

/**
 *
 * @author ferna
 */
public class VentanaAzarFecha1 extends javax.swing.JFrame {

    String[] strGrupoA = EquiposFaseGrupos.grupoA.crearString();
    String[] strGrupoB = EquiposFaseGrupos.grupoB.crearString();
    String[] strGrupoC = EquiposFaseGrupos.grupoC.crearString();
    String[] strGrupoD = EquiposFaseGrupos.grupoD.crearString();
    String[] strGrupoE = EquiposFaseGrupos.grupoE.crearString();
    String[] strGrupoF = EquiposFaseGrupos.grupoF.crearString();
    String[] strGrupoG = EquiposFaseGrupos.grupoG.crearString();
    String[] strGrupoH = EquiposFaseGrupos.grupoH.crearString();
    
    public VentanaAzarFecha1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
 void llenarTablitas(){
    String[] strGrupoA1 = EquiposFaseGrupos.grupoA.crearString();
    String[] strGrupoB1 = EquiposFaseGrupos.grupoB.crearString();
    String[] strGrupoC1 = EquiposFaseGrupos.grupoC.crearString();
    String[] strGrupoD1 = EquiposFaseGrupos.grupoD.crearString();
    String[] strGrupoE1 = EquiposFaseGrupos.grupoE.crearString();
    String[] strGrupoF1 = EquiposFaseGrupos.grupoF.crearString();
    String[] strGrupoG1= EquiposFaseGrupos.grupoG.crearString();
    String[] strGrupoH1 = EquiposFaseGrupos.grupoH.crearString();
     this.jlGrupo1.setListData(strGrupoA1);
        this.jlGrupo2.setListData(strGrupoB1);
        this.jlGrupo3.setListData(strGrupoC1);
        this.jlGrupo4.setListData(strGrupoD1);
        this.jlGrupo5.setListData(strGrupoE1);
        this.jlGrupo6.setListData(strGrupoF1);
        this.jlGrupo7.setListData(strGrupoG1);
        this.jlGrupo8.setListData(strGrupoH1);
 }
     
     
     
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAvanzarFecha2 = new javax.swing.JButton();
        btnSimularFecha1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlGrupo2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlGrupo3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlGrupo4 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlGrupo5 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlGrupo6 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlGrupo7 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlGrupo8 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jlGrupo1 = new javax.swing.JList<>();
        Titulo = new javax.swing.JLabel();
        btnSimularFecha2 = new javax.swing.JButton();
        btnSimularFecha3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtAreaResultados = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(920, 580));
        setResizable(false);
        setSize(new java.awt.Dimension(920, 580));
        getContentPane().setLayout(null);

        btnAvanzarFecha2.setText("AVANZAR A OCTAVOS");
        btnAvanzarFecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarFecha2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvanzarFecha2);
        btnAvanzarFecha2.setBounds(730, 540, 151, 30);

        btnSimularFecha1.setText("SIMULAR FECHA 1");
        btnSimularFecha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimularFecha1MouseClicked(evt);
            }
        });
        btnSimularFecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularFecha1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimularFecha1);
        btnSimularFecha1.setBounds(440, 490, 140, 30);

        jlGrupo2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo2.setOpaque(false);
        jScrollPane1.setViewportView(jlGrupo2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 160, 100);

        jlGrupo3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo3.setOpaque(false);
        jScrollPane3.setViewportView(jlGrupo3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 300, 160, 100);

        jlGrupo4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo4.setOpaque(false);
        jScrollPane4.setViewportView(jlGrupo4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 440, 160, 100);

        jlGrupo5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo5.setOpaque(false);
        jScrollPane5.setViewportView(jlGrupo5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(220, 40, 160, 100);

        jlGrupo6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo6.setOpaque(false);
        jScrollPane6.setViewportView(jlGrupo6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(220, 170, 160, 100);

        jlGrupo7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo7.setOpaque(false);
        jScrollPane7.setViewportView(jlGrupo7);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(220, 300, 160, 100);

        jlGrupo8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo8.setOpaque(false);
        jScrollPane8.setViewportView(jlGrupo8);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(220, 440, 160, 100);

        jlGrupo1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo1.setOpaque(false);
        jScrollPane9.setViewportView(jlGrupo1);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(30, 40, 160, 100);

        Titulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Titulo.setText("RESULTADOS FECHAS");
        getContentPane().add(Titulo);
        Titulo.setBounds(540, 10, 230, 30);

        btnSimularFecha2.setText("SIMULAR FECHA 2");
        btnSimularFecha2.setEnabled(false);
        btnSimularFecha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimularFecha2MouseClicked(evt);
            }
        });
        btnSimularFecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularFecha2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimularFecha2);
        btnSimularFecha2.setBounds(590, 490, 140, 30);

        btnSimularFecha3.setText("SIMULAR FECHA 3");
        btnSimularFecha3.setEnabled(false);
        btnSimularFecha3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimularFecha3MouseClicked(evt);
            }
        });
        btnSimularFecha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularFecha3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimularFecha3);
        btnSimularFecha3.setBounds(740, 490, 140, 30);

        jtxtAreaResultados.setColumns(20);
        jtxtAreaResultados.setRows(5);
        jScrollPane2.setViewportView(jtxtAreaResultados);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane10.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(440, 40, 440, 440);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GRUPO A");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 110, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GRUPO B");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 70, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GRUPO C");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 280, 70, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GRUPO D");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 420, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GRUPO E");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 20, 60, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GRUPO F");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 150, 60, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GRUPO G");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 280, 70, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GRUPO H");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 420, 70, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoOctavos.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 920, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvanzarFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarFecha2ActionPerformed

        VentanaAzarOctavos ventOctavos = new VentanaAzarOctavos();
        ventOctavos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAvanzarFecha2ActionPerformed

    private void btnSimularFecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularFecha1ActionPerformed

        generarResultados();
        llenarTablitas();
        
    }//GEN-LAST:event_btnSimularFecha1ActionPerformed
    void generarResultados() {
        String salida = "";
        int resultados[] = new int[32];
        for (int i = 0; i < 32; i++) {
            resultados[i] = (int) (Math.random() * 6);

        }
        salida += "Partidos Grupo A\n" + strGrupoA[0] + "\t" + resultados[0] + "\t" + strGrupoA[1] + "\t" + resultados[1] + "\n";
        salida += strGrupoA[2] + "\t" + resultados[2] + "\t" + strGrupoA[3] + "\t" + resultados[3] + "\n";
        salida += "\nPartidos Grupo B\n" + strGrupoB[0] + "\t" + resultados[4] + "\t" + strGrupoB[1] + "\t" + resultados[5] + "\n";
        salida += strGrupoB[2] + "\t" + resultados[6] + "\t" + strGrupoB[3] + "\t" + resultados[7] + "\n";
        salida += "\nPartidos Grupo C\n" + strGrupoC[0] + "\t" + resultados[8] + "\t" + strGrupoC[1] + "\t" + resultados[9] + "\n";
        salida += strGrupoC[2] + "\t" + resultados[10] + "\t" + strGrupoC[3] + "\t" + resultados[11] + "\n";
        salida += "\nPartidos Grupo D\n" + strGrupoD[0] + "\t" + resultados[12] + "\t" + strGrupoD[1] + "\t" + resultados[13] + "\n";
        salida += strGrupoD[2] + "\t" + resultados[14] + "\t" + strGrupoD[3] + "\t" + resultados[15] + "\n";
        salida += "\nPartidos Grupo E\n" + strGrupoE[0] + "\t" + resultados[16] + "\t" + strGrupoE[1] + "\t" + resultados[17] + "\n";
        salida += strGrupoE[2] + "\t" + resultados[18] + "\t" + strGrupoE[3] + "\t" + resultados[19] + "\n";
        salida += "\nPartidos Grupo F\n" + strGrupoF[0] + "\t" + resultados[20] + "\t" + strGrupoF[1] + "\t" + resultados[21] + "\n";
        salida += strGrupoF[2] + "\t" + resultados[22] + "\t" + strGrupoF[3] + "\t" + resultados[23] + "\n";
        salida += "\nPartidos Grupo G\n" + strGrupoG[0] + "\t" + resultados[24] + "\t" + strGrupoG[1] + "\t" + resultados[25] + "\n";
        salida += strGrupoG[2] + "\t" + resultados[26] + "\t" + strGrupoG[3] + "\t" + resultados[27] + "\n";
        salida += "\nPartidos Grupo H\n" + strGrupoH[0] + "\t" + resultados[28] + "\t" + strGrupoH[1] + "\t" + resultados[29] + "\n";
        salida += strGrupoH[2] + "\t" + resultados[30] + "\t" + strGrupoH[3] + "\t" + resultados[31] + "\n";
        this.jtxtAreaResultados.setText(salida);
        EquiposFaseGrupos.grupoA.ingresarResultados(resultados[0], resultados[1], strGrupoA[0], strGrupoA[1]);
        EquiposFaseGrupos.grupoA.ingresarResultados(resultados[2], resultados[3], strGrupoA[2], strGrupoA[3]);
        EquiposFaseGrupos.grupoB.ingresarResultados(resultados[4], resultados[5], strGrupoB[0], strGrupoB[1]);
        EquiposFaseGrupos.grupoB.ingresarResultados(resultados[6], resultados[7], strGrupoB[2], strGrupoB[3]);
        EquiposFaseGrupos.grupoC.ingresarResultados(resultados[8], resultados[9], strGrupoC[0], strGrupoC[1]);
        EquiposFaseGrupos.grupoC.ingresarResultados(resultados[10], resultados[11], strGrupoC[2], strGrupoC[3]);
        EquiposFaseGrupos.grupoD.ingresarResultados(resultados[12], resultados[13], strGrupoD[0], strGrupoD[1]);
        EquiposFaseGrupos.grupoD.ingresarResultados(resultados[14], resultados[15], strGrupoD[2], strGrupoD[3]);
        EquiposFaseGrupos.grupoE.ingresarResultados(resultados[16], resultados[17], strGrupoE[0], strGrupoE[1]);
        EquiposFaseGrupos.grupoE.ingresarResultados(resultados[18], resultados[19], strGrupoE[2], strGrupoE[3]);
        EquiposFaseGrupos.grupoF.ingresarResultados(resultados[20], resultados[21], strGrupoF[0], strGrupoF[1]);
        EquiposFaseGrupos.grupoF.ingresarResultados(resultados[22], resultados[23], strGrupoF[2], strGrupoF[3]);
        EquiposFaseGrupos.grupoG.ingresarResultados(resultados[24], resultados[25], strGrupoG[0], strGrupoG[1]);
        EquiposFaseGrupos.grupoG.ingresarResultados(resultados[26], resultados[27], strGrupoG[2], strGrupoG[3]);
        EquiposFaseGrupos.grupoH.ingresarResultados(resultados[28], resultados[29], strGrupoH[0], strGrupoH[1]);
        EquiposFaseGrupos.grupoH.ingresarResultados(resultados[30], resultados[31], strGrupoH[2], strGrupoH[3]);

        EquiposFaseGrupos.ordenarGrupos();
        jTextArea1.setText(EquiposFaseGrupos.imprimirGrupos());
    }
    private void btnSimularFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularFecha2ActionPerformed
        generarResultados();
        llenarTablitas();
    }//GEN-LAST:event_btnSimularFecha2ActionPerformed

    private void btnSimularFecha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularFecha1MouseClicked
        // TODO add your handling code here:
        btnSimularFecha1.setEnabled(false);
        btnSimularFecha2.setEnabled(true);
    }//GEN-LAST:event_btnSimularFecha1MouseClicked

    private void btnSimularFecha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularFecha2MouseClicked
        // TODO add your handling code here:
        btnSimularFecha2.setEnabled(false);
        btnSimularFecha3.setEnabled(true);
    }//GEN-LAST:event_btnSimularFecha2MouseClicked

    private void btnSimularFecha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularFecha3ActionPerformed
        // TODO add your handling code here:
        generarResultados();
        llenarTablitas();
    }//GEN-LAST:event_btnSimularFecha3ActionPerformed

    private void btnSimularFecha3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimularFecha3MouseClicked
        // TODO add your handling code here:
        btnSimularFecha3.setEnabled(false);
        btnAvanzarFecha2.getFocusListeners();
    }//GEN-LAST:event_btnSimularFecha3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarFecha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarFecha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarFecha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAzarFecha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAzarFecha1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnAvanzarFecha2;
    private javax.swing.JButton btnSimularFecha1;
    private javax.swing.JButton btnSimularFecha2;
    private javax.swing.JButton btnSimularFecha3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> jlGrupo1;
    private javax.swing.JList<String> jlGrupo2;
    private javax.swing.JList<String> jlGrupo3;
    private javax.swing.JList<String> jlGrupo4;
    private javax.swing.JList<String> jlGrupo5;
    private javax.swing.JList<String> jlGrupo6;
    private javax.swing.JList<String> jlGrupo7;
    private javax.swing.JList<String> jlGrupo8;
    private javax.swing.JTextArea jtxtAreaResultados;
    // End of variables declaration//GEN-END:variables
}
