
package demoproyecto;

import source.*;
/**
 *
 * @author E2
 */
public class VentanaAzar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAzar
     */
    public VentanaAzar() {
        
        initComponents();
        EquiposFaseGrupos.iniciarCrearGrupos();
        EquiposFaseGrupos.crearGruposAlAzar();
        jlGrupo1.setListData(EquiposFaseGrupos.grupoA.crearString());
        jlGrupo2.setListData(EquiposFaseGrupos.grupoB.crearString());
         jlGrupo3.setListData(EquiposFaseGrupos.grupoC.crearString());
        jlGrupo4.setListData(EquiposFaseGrupos.grupoD.crearString());
        jlGrupo5.setListData(EquiposFaseGrupos.grupoE.crearString());
        jlGrupo6.setListData(EquiposFaseGrupos.grupoF.crearString());
        jlGrupo7.setListData(EquiposFaseGrupos.grupoG.crearString());
        jlGrupo8.setListData(EquiposFaseGrupos.grupoH.crearString());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlGrupo1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlGrupo2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlGrupo3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlGrupo4 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlGrupo5 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlGrupo6 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlGrupo7 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlGrupo8 = new javax.swing.JList<>();
        btnIniciar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jlGrupo1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo1.setOpaque(false);
        jScrollPane1.setViewportView(jlGrupo1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 160, 100);

        jlGrupo2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo2.setOpaque(false);
        jScrollPane2.setViewportView(jlGrupo2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 170, 160, 100);

        jlGrupo3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo3.setOpaque(false);
        jScrollPane3.setViewportView(jlGrupo3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 300, 160, 100);

        jlGrupo4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo4.setOpaque(false);
        jScrollPane4.setViewportView(jlGrupo4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 430, 160, 100);

        jlGrupo5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo5.setOpaque(false);
        jScrollPane5.setViewportView(jlGrupo5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(560, 40, 160, 100);

        jlGrupo6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo6.setOpaque(false);
        jScrollPane6.setViewportView(jlGrupo6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(560, 170, 160, 100);

        jlGrupo7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo7.setOpaque(false);
        jScrollPane7.setViewportView(jlGrupo7);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(560, 300, 160, 100);

        jlGrupo8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo8.setOpaque(false);
        jScrollPane8.setViewportView(jlGrupo8);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(560, 430, 160, 100);

        btnIniciar.setText("INICIAR CAMPEONATO");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(310, 490, 160, 30);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(310, 450, 160, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GRUPO A");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 90, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GRUPO B");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 80, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GRUPO C");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 280, 80, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GRUPO D");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 410, 80, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GRUPO E");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 20, 80, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GRUPO F");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(560, 150, 80, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GRUPO G");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 280, 80, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GRUPO H");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 410, 80, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMundial6.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 750, 550);

        setSize(new java.awt.Dimension(750, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaSeleccionarModo regresar = new VentanaSeleccionarModo();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        VentanaAzarFecha1 fecha1 =new VentanaAzarFecha1();
        fecha1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAzar().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JList<String> jlGrupo1;
    public javax.swing.JList<String> jlGrupo2;
    public javax.swing.JList<String> jlGrupo3;
    public javax.swing.JList<String> jlGrupo4;
    public javax.swing.JList<String> jlGrupo5;
    public javax.swing.JList<String> jlGrupo6;
    public javax.swing.JList<String> jlGrupo7;
    public javax.swing.JList<String> jlGrupo8;
    // End of variables declaration//GEN-END:variables
}
