/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoproyecto;

import java.awt.Color;
import java.util.Vector;

/**
 *
 * @author E2
 */
public class VentanaManual extends javax.swing.JFrame {

    /**
     * Creates new form VentanaManual
     */
    Vector<String> listaEquipos;
    Vector<String> grupo1;
    Vector<String> grupo2;
    Vector<String> grupo3;
    Vector<String> grupo4;
    Vector<String> grupo5;
    Vector<String> grupo6;
    Vector<String> grupo7;
    Vector<String> grupo8;
    public VentanaManual() {
        initComponents();
        listaEquipos = new Vector<String>();
        grupo1 = new Vector<String>();
        grupo2 = new Vector<String>();
        grupo3 = new Vector<String>();
        grupo4 = new Vector<String>();
        grupo5 = new Vector<String>();
        grupo6 = new Vector<String>();
        grupo7 = new Vector<String>();
        grupo8 = new Vector<String>();
        cargarEquipos();
    }
    public void cargarEquipos(){
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        listaEquipos.add("Rusia");
        
              
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlPaises = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlGrupo1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlGrupo2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlGrupo3 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlGrupo4 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlGrupo5 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlGrupo6 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlGrupo7 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jlGrupo8 = new javax.swing.JList<>();
        btnRegresar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jlPaises.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlPaises.setOpaque(false);
        jlPaises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlPaisesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlPaises);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 200, 510);

        jScrollPane2.setOpaque(false);

        jlGrupo1.setOpaque(false);
        jScrollPane2.setViewportView(jlGrupo1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(280, 20, 140, 90);

        jlGrupo2.setOpaque(false);
        jScrollPane3.setViewportView(jlGrupo2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(440, 20, 150, 90);

        jlGrupo3.setOpaque(false);
        jScrollPane4.setViewportView(jlGrupo3);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(610, 20, 150, 90);

        jlGrupo4.setOpaque(false);
        jScrollPane5.setViewportView(jlGrupo4);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(280, 150, 140, 90);

        jlGrupo5.setOpaque(false);
        jScrollPane6.setViewportView(jlGrupo5);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(440, 150, 150, 90);

        jlGrupo6.setOpaque(false);
        jScrollPane7.setViewportView(jlGrupo6);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(610, 150, 150, 90);

        jlGrupo7.setOpaque(false);
        jScrollPane8.setViewportView(jlGrupo7);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(280, 280, 140, 90);

        jlGrupo8.setOpaque(false);
        jScrollPane9.setViewportView(jlGrupo8);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(440, 280, 150, 90);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(280, 430, 160, 30);

        btnIniciar.setText("INICIAR CAMPEONATO");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(490, 430, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMundial4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 550);

        setSize(new java.awt.Dimension(800, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaSeleccionarModo regresar = new VentanaSeleccionarModo();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        VentanaFecha1Manual fase =new VentanaFecha1Manual();
        fase.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void jlPaisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlPaisesMouseClicked
        // TODO add your handling code here:
        VentanaAñadirManual ventana = new  VentanaAñadirManual();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlPaisesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaManual().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> jlGrupo1;
    private javax.swing.JList<String> jlGrupo2;
    private javax.swing.JList<String> jlGrupo3;
    private javax.swing.JList<String> jlGrupo4;
    private javax.swing.JList<String> jlGrupo5;
    private javax.swing.JList<String> jlGrupo6;
    private javax.swing.JList<String> jlGrupo7;
    private javax.swing.JList<String> jlGrupo8;
    private javax.swing.JList<String> jlPaises;
    // End of variables declaration//GEN-END:variables
}
