/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoproyecto;

/**
 *
 * @author E2
 */
public class VentanaAñadirManual extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAñadirManual
     */
    public VentanaAñadirManual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo1 = new javax.swing.JButton();
        btnGrupo2 = new javax.swing.JButton();
        btnGrupo3 = new javax.swing.JButton();
        btnGrupo4 = new javax.swing.JButton();
        btnGrupo5 = new javax.swing.JButton();
        btnGrupo6 = new javax.swing.JButton();
        btnGrupo7 = new javax.swing.JButton();
        btnGrupo8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btnGrupo1.setText("GRUPO 1");
        getContentPane().add(btnGrupo1);
        btnGrupo1.setBounds(50, 100, 90, 40);

        btnGrupo2.setText("GRUPO 2");
        getContentPane().add(btnGrupo2);
        btnGrupo2.setBounds(150, 100, 90, 40);

        btnGrupo3.setText("GRUPO 3");
        getContentPane().add(btnGrupo3);
        btnGrupo3.setBounds(250, 100, 90, 40);

        btnGrupo4.setText("GRUPO 4");
        getContentPane().add(btnGrupo4);
        btnGrupo4.setBounds(350, 100, 90, 40);

        btnGrupo5.setText("GRUPO 5");
        getContentPane().add(btnGrupo5);
        btnGrupo5.setBounds(50, 160, 90, 40);

        btnGrupo6.setText("GRUPO 6");
        getContentPane().add(btnGrupo6);
        btnGrupo6.setBounds(150, 160, 90, 40);

        btnGrupo7.setText("GRUPO 7");
        getContentPane().add(btnGrupo7);
        btnGrupo7.setBounds(250, 160, 90, 40);

        btnGrupo8.setText("GRUPO 8");
        getContentPane().add(btnGrupo8);
        btnGrupo8.setBounds(350, 160, 90, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText(" SELECCIONAR GRUPO ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 390, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo5.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 280);

        setSize(new java.awt.Dimension(492, 259));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAñadirManual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrupo1;
    private javax.swing.JButton btnGrupo2;
    private javax.swing.JButton btnGrupo3;
    private javax.swing.JButton btnGrupo4;
    private javax.swing.JButton btnGrupo5;
    private javax.swing.JButton btnGrupo6;
    private javax.swing.JButton btnGrupo7;
    private javax.swing.JButton btnGrupo8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
