
package demoproyecto;

import source.*;
/**
 *
 * @author E2
 */
public class VentanaAzar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAzar
     */
    public VentanaAzar() {
        
        initComponents();
        EquiposFaseGrupos.iniciarCrearGrupos();
        EquiposFaseGrupos.crearGruposAlAzar();
        jlGrupo1.setListData(EquiposFaseGrupos.grupoA.crearString());
        jlGrupo2.setListData(EquiposFaseGrupos.grupoB.crearString());
         jlGrupo3.setListData(EquiposFaseGrupos.grupoC.crearString());
        jlGrupo4.setListData(EquiposFaseGrupos.grupoD.crearString());
        jlGrupo5.setListData(EquiposFaseGrupos.grupoE.crearString());
        jlGrupo6.setListData(EquiposFaseGrupos.grupoF.crearString());
        jlGrupo7.setListData(EquiposFaseGrupos.grupoG.crearString());
        jlGrupo8.setListData(EquiposFaseGrupos.grupoH.crearString());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlGrupo1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlGrupo2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlGrupo3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlGrupo4 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlGrupo5 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlGrupo6 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlGrupo7 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlGrupo8 = new javax.swing.JList<>();
        btnIniciar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jlGrupo1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo1.setOpaque(false);
        jScrollPane1.setViewportView(jlGrupo1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 10, 160, 100);

        jlGrupo2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo2.setOpaque(false);
        jScrollPane2.setViewportView(jlGrupo2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 130, 160, 100);

        jlGrupo3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo3.setOpaque(false);
        jScrollPane3.setViewportView(jlGrupo3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(40, 240, 160, 100);

        jlGrupo4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo4.setOpaque(false);
        jScrollPane4.setViewportView(jlGrupo4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 350, 160, 100);

        jlGrupo5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo5.setOpaque(false);
        jScrollPane5.setViewportView(jlGrupo5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(560, 20, 160, 100);

        jlGrupo6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo6.setOpaque(false);
        jScrollPane6.setViewportView(jlGrupo6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(560, 130, 160, 100);

        jlGrupo7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo7.setOpaque(false);
        jScrollPane7.setViewportView(jlGrupo7);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(560, 240, 160, 100);

        jlGrupo8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlGrupo8.setOpaque(false);
        jScrollPane8.setViewportView(jlGrupo8);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(560, 350, 160, 100);

        btnIniciar.setText("INICIAR CAMPEONATO");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(560, 480, 160, 30);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(30, 480, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMundial6.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 530);

        setSize(new java.awt.Dimension(750, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaSeleccionarModo regresar = new VentanaSeleccionarModo();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        VentanaAzarFecha1 fecha1 =new VentanaAzarFecha1();
        fecha1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAzar().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JList<String> jlGrupo1;
    public javax.swing.JList<String> jlGrupo2;
    public javax.swing.JList<String> jlGrupo3;
    public javax.swing.JList<String> jlGrupo4;
    public javax.swing.JList<String> jlGrupo5;
    public javax.swing.JList<String> jlGrupo6;
    public javax.swing.JList<String> jlGrupo7;
    public javax.swing.JList<String> jlGrupo8;
    // End of variables declaration//GEN-END:variables
}
